// <auto-generated />
using System;
using MeetingAssistant.Infrastructure.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeetingAssistant.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601120000_AddMeetingTagSuggestions")]
    partial class AddMeetingTagSuggestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeetingAssistant.Features.ActionItems.Models.Entities.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExternalProvider")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExternalTaskUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SyncMissingAssigneeReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToParticipantId");

                    b.HasIndex("AssignedToUserId", "Status")
                        .HasDatabaseName("IX_ActionItems_AssignedToUserId_Status");

                    b.HasIndex("MeetingId", "Status")
                        .HasDatabaseName("IX_ActionItems_MeetingId_Status");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("IX_ActionItems_OrganizationId_Status");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("MeetingAssistant.Features.ActionItems.Models.Entities.ExternalAccountLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenProtected")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExternalUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OrganizationId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalAccountLinks_UserId_OrgId_Provider");

                    b.ToTable("ExternalAccountLinks");
                });

            modelBuilder.Entity("MeetingAssistant.Features.ActionItems.Models.Entities.ExternalMemberMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalMemberId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalMemberMappings_OrgId_UserId_Provider");

                    b.ToTable("ExternalMemberMappings");
                });

            modelBuilder.Entity("MeetingAssistant.Features.ActionItems.Models.Entities.OrganizationIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Type")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationIntegrations_OrgId_Type");

                    b.ToTable("OrganizationIntegrations");
                });

            modelBuilder.Entity("MeetingAssistant.Features.ActionItems.Models.Entities.OrganizationIntegrationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedProviderPayload")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedListId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SelectedProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationIntegrationConfigs_OrgId_Provider");

                    b.ToTable("OrganizationIntegrationConfigs");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Identity.Entites.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileAvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MeetingAssistant.Features.Identity.Entites.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GracePeriodExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.AiAssistantTraceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AudioDurationMs")
                        .HasColumnType("integer");

                    b.Property<int?>("CharactersCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParticipantIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponsePayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StepEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StepModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StepProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StepType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StepVoice")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<string>("TurnId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_AiAssistantTraceEvents_OrganizationId");

                    b.HasIndex("OrganizationId", "MeetingId", "OccurredAtUtc")
                        .HasDatabaseName("IX_AiAssistantTraceEvents_Org_Meeting_OccurredAtUtc");

                    b.HasIndex("OrganizationId", "MeetingId", "SessionId", "TurnId", "Sequence")
                        .HasDatabaseName("IX_AiAssistantTraceEvents_Turn_Sequence");

                    b.ToTable("AiAssistantTraceEvents");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.MeetingSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique()
                        .HasDatabaseName("IX_MeetingSummaries_MeetingId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_MeetingSummaries_OrganizationId");

                    b.ToTable("MeetingSummaries");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.MeetingTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SegmentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SttModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique()
                        .HasDatabaseName("IX_MeetingTranscripts_MeetingId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_MeetingTranscripts_OrganizationId");

                    b.ToTable("MeetingTranscripts");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.ParticipantAudioFragment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EgressEndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EgressId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("EgressStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParticipantAudioTrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantUserId")
                        .HasColumnType("uuid");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StorageAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StorageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("TrackPublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrackSid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EgressId")
                        .HasDatabaseName("IX_ParticipantAudioFragments_EgressId");

                    b.HasIndex("ParticipantAudioTrackId")
                        .HasDatabaseName("IX_ParticipantAudioFragments_ParticipantAudioTrackId");

                    b.HasIndex("TrackSid")
                        .HasDatabaseName("IX_ParticipantAudioFragments_TrackSid");

                    b.HasIndex("MeetingId", "Status")
                        .HasDatabaseName("IX_ParticipantAudioFragments_MeetingId_Status");

                    b.HasIndex("MeetingId", "TrackSid")
                        .IsUnique()
                        .HasDatabaseName("UX_ParticipantAudioFragments_MeetingId_TrackSid");

                    b.HasIndex("MeetingId", "ParticipantUserId", "TrackPublishedAtUtc")
                        .HasDatabaseName("IX_ParticipantAudioFragments_Meeting_Participant_PublishedAt");

                    b.HasIndex("OrganizationId", "MeetingId", "ParticipantUserId")
                        .HasDatabaseName("IX_ParticipantAudioFragments_Org_Meeting_Participant");

                    b.ToTable("ParticipantAudioFragments");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.ParticipantAudioTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantUserId")
                        .HasColumnType("uuid");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_ParticipantAudioTracks_OrganizationId");

                    b.HasIndex("MeetingId", "ParticipantUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ParticipantAudioTracks_MeetingId_ParticipantUserId");

                    b.HasIndex("MeetingId", "Status")
                        .HasDatabaseName("IX_ParticipantAudioTracks_MeetingId_Status");

                    b.ToTable("ParticipantAudioTracks");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactIdsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ArtifactType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedHangfireJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StepType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StepId")
                        .HasDatabaseName("IX_PostMeetingProcessingEvents_StepId");

                    b.HasIndex("RunId", "OccurredAtUtc")
                        .HasDatabaseName("IX_PostMeetingProcessingEvents_Run_OccurredAt");

                    b.HasIndex("OrganizationId", "MeetingId", "OccurredAtUtc")
                        .HasDatabaseName("IX_PostMeetingProcessingEvents_Org_Meeting_OccurredAt");

                    b.ToTable("PostMeetingProcessingEvents");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PipelineGenerationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedHangfireJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("IX_PostMeetingProcessingRuns_Org_Status");

                    b.HasIndex("OrganizationId", "MeetingId", "CreatedAtUtc")
                        .HasDatabaseName("IX_PostMeetingProcessingRuns_Org_Meeting_CreatedAt");

                    b.HasIndex("OrganizationId", "MeetingId", "PipelineGenerationId")
                        .IsUnique()
                        .HasDatabaseName("UX_PostMeetingProcessingRuns_Org_Meeting_Generation");

                    b.ToTable("PostMeetingProcessingRuns");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactIdsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ArtifactType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedHangfireJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StepType")
                        .IsUnique()
                        .HasDatabaseName("UX_PostMeetingProcessingSteps_Run_StepType");

                    b.HasIndex("OrganizationId", "MeetingId", "Status")
                        .HasDatabaseName("IX_PostMeetingProcessingSteps_Org_Meeting_Status");

                    b.HasIndex("OrganizationId", "MeetingId", "StepType")
                        .HasDatabaseName("IX_PostMeetingProcessingSteps_Org_Meeting_StepType");

                    b.ToTable("PostMeetingProcessingSteps");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.SessionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParticipantUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("IX_SessionEvents_ExternalEventId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_SessionEvents_OrganizationId");

                    b.HasIndex("ParticipantUserId");

                    b.HasIndex("MeetingId", "OccurredAtUtc")
                        .HasDatabaseName("IX_SessionEvents_MeetingId_OccurredAtUtc");

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AiAssistantEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RecurringOccurrenceIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RecurringSeriesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RoomActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_Meetings_OrganizationId");

                    b.HasIndex("OrganizationId", "ScheduledStartUtc")
                        .HasDatabaseName("IX_Meetings_OrgId_ScheduledStartUtc");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("IX_Meetings_OrgId_Status");

                    b.HasIndex("RecurringSeriesId", "RecurringOccurrenceIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_Meetings_RecurringSeriesId_RecurringOccurrenceIndex")
                        .HasFilter("\"RecurringSeriesId\" IS NOT NULL AND \"RecurringOccurrenceIndex\" IS NOT NULL");

                    b.HasIndex("OrganizationId", "RecurringSeriesId", "ScheduledStartUtc")
                        .HasDatabaseName("IX_Meetings_OrgId_RecurringSeriesId_ScheduledStartUtc");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.MeetingMeetingTag", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeetingTagId")
                        .HasColumnType("uuid");

                    b.HasKey("MeetingId", "MeetingTagId");

                    b.HasIndex("MeetingTagId");

                    b.ToTable("MeetingMeetingTags");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.MeetingParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<int>("MeetingRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_MeetingParticipants_OrganizationId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MeetingParticipants_UserId");

                    b.HasIndex("MeetingId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_MeetingParticipants_MeetingId_UserId");

                    b.ToTable("MeetingParticipants");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.MeetingTagSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeetingTagId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SuggestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SummaryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagColorSnapshot")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("TagNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("TranscriptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingTagId");

                    b.HasIndex("MeetingId", "MeetingTagId", "Status")
                        .IsUnique()
                        .HasDatabaseName("UX_MeetingTagSuggestions_Meeting_Tag_Pending")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("OrganizationId", "MeetingId", "Status")
                        .HasDatabaseName("IX_MeetingTagSuggestions_Org_Meeting_Status");

                    b.HasIndex("OrganizationId", "MeetingTagId", "Status")
                        .HasDatabaseName("IX_MeetingTagSuggestions_Org_Tag_Status");

                    b.ToTable("MeetingTagSuggestions");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.RecurringMeetingSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ScheduledEndTimeUtc")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ScheduledStartTimeUtc")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("IX_RecurringMeetingSeries_OrganizationId_Status");

                    b.ToTable("RecurringMeetingSeries");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Organizations.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("EmailWhitelist")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Organizations.Models.MeetingTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_MeetingTags_OrganizationId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MeetingTags_OrgId_LowerName_ActiveOnly")
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("MeetingTags");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Organizations.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("MeetingAssistant.Features.Organizations.Models.UserOrgMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ContextStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("JobRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrgRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserOrgMemberships_UserId_ActiveOnly")
                        .HasFilter("\"IsEnabled\" = true");

                    b.ToTable("UserOrgMemberships");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Rag.Models.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<int>("ArtifactType")
                        .HasColumnType("integer");

                    b.Property<int>("ArtifactVersion")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("EmbeddingDimension")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EmbeddingVectorText")
                        .IsRequired()
                        .HasColumnType("vector")
                        .HasColumnName("Embedding");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IndexGenerationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("UX_KnowledgeChunks_Document_ChunkIndex");

                    b.HasIndex("OrganizationId", "ContentHash")
                        .HasDatabaseName("IX_KnowledgeChunks_Org_ContentHash");

                    b.HasIndex("OrganizationId", "IndexGenerationId")
                        .HasDatabaseName("IX_KnowledgeChunks_Org_IndexGeneration");

                    b.HasIndex("OrganizationId", "MeetingId")
                        .HasDatabaseName("IX_KnowledgeChunks_Org_Meeting");

                    b.HasIndex("OrganizationId", "ArtifactType", "ArtifactId", "ArtifactVersion")
                        .HasDatabaseName("IX_KnowledgeChunks_Org_Artifact");

                    b.HasIndex("OrganizationId", "Visibility", "IsCurrent", "EmbeddingModel", "EmbeddingDimension")
                        .HasDatabaseName("IX_KnowledgeChunks_Org_Visibility_Current_Model_Dim");

                    b.ToTable("KnowledgeChunks");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Rag.Models.KnowledgeChunkTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KnowledgeChunkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeetingTagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagColorSnapshot")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("TagNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentId");

                    b.HasIndex("MeetingTagId");

                    b.HasIndex("KnowledgeChunkId", "MeetingTagId")
                        .IsUnique()
                        .HasDatabaseName("UX_KnowledgeChunkTags_Chunk_Tag");

                    b.HasIndex("OrganizationId", "KnowledgeDocumentId")
                        .HasDatabaseName("IX_KnowledgeChunkTags_Org_Document");

                    b.HasIndex("OrganizationId", "MeetingTagId", "KnowledgeChunkId")
                        .HasDatabaseName("IX_KnowledgeChunkTags_Org_Tag_Chunk");

                    b.ToTable("KnowledgeChunkTags");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Rag.Models.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<int>("ArtifactType")
                        .HasColumnType("integer");

                    b.Property<int>("ArtifactVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmbeddingDimension")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IndexGenerationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("OrganizationId", "ContentHash")
                        .HasDatabaseName("IX_KnowledgeDocuments_Org_ContentHash");

                    b.HasIndex("OrganizationId", "IndexGenerationId")
                        .HasDatabaseName("IX_KnowledgeDocuments_Org_IndexGeneration");

                    b.HasIndex("OrganizationId", "ArtifactType", "ArtifactId", "ArtifactVersion")
                        .HasDatabaseName("IX_KnowledgeDocuments_Org_Artifact");

                    b.HasIndex("OrganizationId", "Visibility", "IsCurrent", "MeetingId")
                        .HasDatabaseName("IX_KnowledgeDocuments_Org_Visibility_Current_Meeting");

                    b.HasIndex("OrganizationId", "ArtifactType", "ArtifactId", "ArtifactVersion", "IndexGenerationId")
                        .IsUnique()
                        .HasDatabaseName("UX_KnowledgeDocuments_Org_Artifact_Generation");

                    b.ToTable("KnowledgeDocuments");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Tasks.Models.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ReminderAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId", "Status")
                        .HasDatabaseName("IX_Reminders_TargetUserId_Status");

                    b.HasIndex("MeetingId", "Scope", "Status")
                        .HasDatabaseName("IX_Reminders_MeetingId_Scope_Status");

                    b.HasIndex("OrganizationId", "Status", "ReminderAtUtc")
                        .HasDatabaseName("IX_Reminders_Org_Status_ReminderAtUtc");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MeetingAssistant.Features.ActionItems.Models.Entities.ActionItem", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.MeetingParticipant", "AssignedToParticipant")
                        .WithMany()
                        .HasForeignKey("AssignedToParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToParticipant");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAssistant.Features.ActionItems.Models.Entities.ExternalAccountLink", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetingAssistant.Features.ActionItems.Models.Entities.ExternalMemberMapping", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Identity.Entites.RefreshToken", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.AiAssistantTraceEvent", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.MeetingSummary", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.MeetingTranscript", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.ParticipantAudioFragment", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.LiveSession.Models.ParticipantAudioTrack", "ParticipantAudioTrack")
                        .WithMany("Fragments")
                        .HasForeignKey("ParticipantAudioTrackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Meeting");

                    b.Navigation("ParticipantAudioTrack");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.ParticipantAudioTrack", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingEvent", b =>
                {
                    b.HasOne("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingRun", "Run")
                        .WithMany("Events")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingStep", "Step")
                        .WithMany("Events")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Run");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingRun", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingStep", b =>
                {
                    b.HasOne("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingRun", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.SessionEvent", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ParticipantUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.Meeting", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.RecurringMeetingSeries", "RecurringSeries")
                        .WithMany("Meetings")
                        .HasForeignKey("RecurringSeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("MeetingAssistant.Features.Meetings.Models.RecurrenceConfig", "RecurrenceConfig", b1 =>
                        {
                            b1.Property<Guid>("MeetingId");

                            b1.Property<string>("DaysOfWeek");

                            b1.Property<DateTime?>("EndsAtUtc");

                            b1.Property<int>("Frequency");

                            b1.Property<int>("Interval");

                            b1.HasKey("MeetingId");

                            b1.ToTable("Meetings");

                            b1
                                .ToJson("RecurrenceConfig")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MeetingId");
                        });

                    b.Navigation("RecurrenceConfig");

                    b.Navigation("RecurringSeries");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.MeetingMeetingTag", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany("Tags")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Organizations.Models.MeetingTag", "MeetingTag")
                        .WithMany()
                        .HasForeignKey("MeetingTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("MeetingTag");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.MeetingParticipant", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany("Participants")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.MeetingTagSuggestion", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Organizations.Models.MeetingTag", "MeetingTag")
                        .WithMany()
                        .HasForeignKey("MeetingTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("MeetingTag");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Organizations.Models.Invitation", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Organizations.Models.Organization", "Organization")
                        .WithMany("Invitations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("RevokedByUserId");

                    b.Navigation("InvitedByUser");

                    b.Navigation("Organization");

                    b.Navigation("RevokedByUser");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Organizations.Models.UserOrgMembership", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Organizations.Models.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Rag.Models.KnowledgeChunk", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Rag.Models.KnowledgeDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Rag.Models.KnowledgeChunkTag", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Rag.Models.KnowledgeChunk", "KnowledgeChunk")
                        .WithMany("Tags")
                        .HasForeignKey("KnowledgeChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Rag.Models.KnowledgeDocument", "KnowledgeDocument")
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Organizations.Models.MeetingTag", "MeetingTag")
                        .WithMany()
                        .HasForeignKey("MeetingTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KnowledgeChunk");

                    b.Navigation("KnowledgeDocument");

                    b.Navigation("MeetingTag");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Rag.Models.KnowledgeDocument", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Meetings.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MeetingAssistant.Features.Identity.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingAssistant.Features.Identity.Entites.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.ParticipantAudioTrack", b =>
                {
                    b.Navigation("Fragments");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingRun", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MeetingAssistant.Features.LiveSession.Models.PostProcessing.PostMeetingProcessingStep", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.Meeting", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Meetings.Models.RecurringMeetingSeries", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Organizations.Models.Organization", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Rag.Models.KnowledgeChunk", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MeetingAssistant.Features.Rag.Models.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
